# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ccorecpp <- function(u, v, bw, M) {
    .Call('rcd_ccorecpp', PACKAGE = 'rcd', u, v, bw, M)
}

ccorecppabs <- function(u, v, bw, M) {
    .Call('rcd_ccorecppabs', PACKAGE = 'rcd', u, v, bw, M)
}

rcpp_distance <- function(mat) {
    .Call('rcd_rcpp_distance', PACKAGE = 'rcd', mat)
}

rcpp_parallel_distance <- function(mat) {
    .Call('rcd_rcpp_parallel_distance', PACKAGE = 'rcd', mat)
}

