# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ccorecpp <- function(u, v, bw) {
    .Call('rcd_ccorecpp', PACKAGE = 'rcd', u, v, bw)
}

ccorecppabs <- function(u, v, bw) {
    .Call('rcd_ccorecppabs', PACKAGE = 'rcd', u, v, bw)
}

rcpp_distance <- function(mat) {
    .Call('rcd_rcpp_distance', PACKAGE = 'rcd', mat)
}

rcpp_parallel_distance <- function(mat) {
    .Call('rcd_rcpp_parallel_distance', PACKAGE = 'rcd', mat)
}

Kcpp <- function(u) {
    .Call('rcd_Kcpp', PACKAGE = 'rcd', u)
}

PKcpp <- function(x, xi, h) {
    .Call('rcd_PKcpp', PACKAGE = 'rcd', x, xi, h)
}

kdendcpp <- function(x, X, h) {
    .Call('rcd_kdendcpp', PACKAGE = 'rcd', x, X, h)
}

kdendveccpp <- function(X, h) {
    .Call('rcd_kdendveccpp', PACKAGE = 'rcd', X, h)
}

